# Generated by Django 3.0.7 on 2020-07-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
