# Generated by Django 3.0.7 on 2020-07-30 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersAPI', '0002_user_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
